import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lato, Manrope } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const waitingfortheSunrise = localFont({
  src: "./fonts/WaitingfortheSunrise-Regular.ttf",
  variable: "--font-waiting-for-sunrise",
  weight: "100 900",
});

const latoRegular = Lato({
  weight: "400",
  variable: "--font-lato-regular",
  subsets: ["latin"],
});

const manropeSemibold = Manrope({
  weight: "600",
  variable: "--font-manrope-semibold",
  subsets: ["latin"],
});

const manropeBold = Manrope({
  weight: "800",
  variable: "--font-manrope-bold",
  subsets: ["latin"],
});

const manropeMedium = Manrope({
  weight: "500",
  variable: "--font-manrope-medium",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${waitingfortheSunrise.variable} ${latoRegular.variable} ${manropeSemibold.variable} ${manropeMedium.variable} ${manropeBold.variable} bg-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
